import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Hand-written guide content. Add doc IDs here as real guides are written
  // (e.g. 'getting-started', 'error-handling', 'local-vs-cloud').
  docsSidebar: ['intro'],

  // Generated from docs/api/ by the API doc pipeline; see scripts/generate-api-docs.ps1.
  // Do not hand-edit files under docs/api/; regenerate them instead.
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
